### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by LinXiaoTao** [jaredrummler/html-builder#1]
Consider providing StringBuild operations so that objects can be reused
```
 private final StringBuilder html = new StringBuilder();
```

**Comment by jaredrummler** [comment]
HtmlBuilder wraps StringBuilder. I'm not quite sure what you mean. Will you please provide additional details?  Thanks.

**Comment by jaredrummler** [comment]
Closing for now. May reopen if additional information is provided.

**Comment by LinXiaoTao** [comment]
I'm sorry, I may not express my meaning.
I mean if I want to delete characters, I have to re new the object, because I can't operate StringBuilder
