### ISSUE TITLE
not showing images

### ISSUE THREAD

**Issue by mjalijani** [jaredrummler/html-builder#10]
does not load images 
sample image : `<a href=\"http://www.sakhtemanchi.com/%d8%b1%d9%86%da%af-%d9%86%d8%b3%d9%88%d8%b2-%da%86%db%8c%d8%b3%d8%aa%d8%9f/\">`

**Comment by jaredrummler** [comment]
You need to add an Http.ImageGetting. See the new HTML DSL and demo for examples.
