### ISSUE TITLE
clickable text or link ?

### ISSUE THREAD

**Issue by quarks3k** [jaredrummler/html-builder#7]
I really appreciate effort you have done to create a Html Builder its nice library.I would like to have feature to make link clickable with appropriate listener interface provided in  builder.

**Comment by zhangchaoxu** [comment]
looking forward to this feature.

**Comment by jaredrummler** [comment]
I updated the library. Example usage for a clickable link:

```kotlin
val html = html {
    a {
        href = "https://github.com/jaredrummler"
        text = strong("Github")
    }
}
textView.text = HtmlCompat.fromHtml(
    html.render(), HtmlCompat.FROM_HTML_MODE_LEGACY
)
textView.movementMethod = LinkMovementMethod.getInstance()
```
