### ISSUE TITLE
Escaping Text and Support For String Resources

### ISSUE THREAD

**Issue by quarks3k** [jaredrummler/html-builder#8]
Hi can you provide support for String Res in text() function.When we pass the text / append it please provide parameter if we want to escape the text with Html.escapeHtml. When we pass symbols it does not escape automatically and spoils the html text . It would be very nice if you provide Boolean to set if we want to escape the text when we append it.

**Comment by jaredrummler** [comment]
I re-wrote the library. You can use `unsafe` for escaping HTML
